const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#7C3AED",
    background: "#ffffff",
    foreground: "#0a0a0a",
    card: "#f9f9f9",
    cardForeground: "#0a0a0a",
    primary: "#7C3AED",
    primaryForeground: "#ffffff",
    secondary: "#f0f0f0",
    secondaryForeground: "#1a1a1a",
    muted: "#f0f0f0",
    mutedForeground: "#737373",
    accent: "#a855f7",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e5e5e5",
    input: "#e5e5e5",
  },
  dark: {
    text: "#f0e8ff",
    tint: "#a78bfa",
    background: "#08030f",
    foreground: "#f0e8ff",
    card: "#110822",
    cardForeground: "#f0e8ff",
    primary: "#7C3AED",
    primaryForeground: "#ffffff",
    secondary: "#1a0d2e",
    secondaryForeground: "#c4b5fd",
    muted: "#1a0d2e",
    mutedForeground: "#7c6a9e",
    accent: "#5b21b6",
    accentForeground: "#f0e8ff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#2d1f45",
    input: "#2d1f45",
    // Custom psytrance extras
    glowPrimary: "#7C3AED",
    glowCyan: "#06b6d4",
    glowMagenta: "#d946ef",
    glowGreen: "#22c55e",
    surface: "#110822",
    surfaceElevated: "#1a0d2e",
  },
  radius: 16,
};

export default colors;
